[workspace]
members = [
    "xdp-guard",
    "xdp-guard-common",
    "xdp-guard-ebpf",
    "xtask",
]
resolver = "2"

[workspace.package]
version = "0.1.1"
edition = "2021"
authors = ["Rahad Bhuiya <rahadbhuiya2021@gmail.com>"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/rahadbhuiya/xdp-guard"
