[package]
name = "xdp-guard-common"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[features]
default = []
user = ["dep:aya"]

[dependencies]
bytemuck = { version = "1.16", default-features = false, features = ["derive"] }
aya = { version = "0.13", default-features = false, optional = true }
